/*
CREATED BY: Aimal Khan
CREATE DATE: 24/02/2024
DESCRIPTION: list of customer names, first and last names, next to all the invoices generated by that customer??
*/
SELECT
	*
FROM
	Invoice
INNER JOIN
	Customer
ON
	Invoice.CustomerId = Customer.CustomerId
ORDER BY
	Customer.CustomerId;